import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { AppBar, Button, Drawer } from "@mui/material"
import MenuDrawer from "./components/menudrawer"


 export default function RootLayout(props) {
   return (
     <html lang="en">
       <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AppBar>
              <MenuDrawer/>
              Demo App
            </AppBar>
              {props.children}
          </ThemeProvider>
        </AppRouterCacheProvider>
       </body>
     </html>
   );
 }


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
